### ISSUE TITLE
Implement Client methods

### ISSUE THREAD

**Issue by SteveCookTU** [zaksabeast/nex-rs#2]

**Comment by SteveCookTU** [comment]
#1

**Comment by SteveCookTU** [comment]
Looking at the ping and kick timers, before implementing I was curious if that would be better handled by the server instances? I don't believe the client should have access to tell the server to kick it, the server should handle removing clients itself.

**Comment by zaksabeast** [comment]
Not letting the client control when the server kicks is definitely a good idea.

Although I don't think that's quite what is happening here.  Instead of a `Client`, think of these as `ClientConnection`s that represent a connection to each client.

At some point the server needs to hold information about each client, such as individual session ids and timeout times.  The ping and kick timers aren't the client telling the server when to ping and kick, it's where the server stores information about each individual client.

What are thoughts on renaming `Client` to `ClientConnection`?

**Comment by SteveCookTU** [comment]
> What are thoughts on renaming `Client` to `ClientConnection`?

I think this would be the best. Since the original library uses the server instance to kick during the loop has there been any thought on how to call that from within the connection instance?

**Comment by zaksabeast** [comment]
I haven't given it much thought.

Off the top of my head, I lean towards `Server::listen` starting additional threads for kicking and pinging.  Thoughts on that approach?
